// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkWV2gjhmg9JrSkXcUG2yswNE9P6ZznkI',
    appId: '1:423433045887:web:e3281e995b8ff405ba7c4a',
    messagingSenderId: '423433045887',
    projectId: 'msx-plus',
    authDomain: 'msx-plus.firebaseapp.com',
    databaseURL: 'https://msx-plus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'msx-plus.appspot.com',
    measurementId: 'G-BQQM9XPVJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFlHfLdL1HOoj0G2rgaYbbM4cX-o1S13w',
    appId: '1:423433045887:android:0434fcc45e950484ba7c4a',
    messagingSenderId: '423433045887',
    projectId: 'msx-plus',
    databaseURL: 'https://msx-plus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'msx-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCglm7ccHCrHYwPahSljf1IUDgRp8tWVfw',
    appId: '1:423433045887:ios:0b2293084681254aba7c4a',
    messagingSenderId: '423433045887',
    projectId: 'msx-plus',
    databaseURL: 'https://msx-plus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'msx-plus.appspot.com',
    iosBundleId: 'com.example.stockPriceForecastingForMsx',
  );
}
